// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, user_id, asset, balance
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, asset, balance
`

type CreateAccountParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Asset   string
	Balance pgtype.Numeric
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Asset,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Balance,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, asset, balance FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Balance,
	)
	return i, err
}

const getAccountByUserAsset = `-- name: GetAccountByUserAsset :one
SELECT id, user_id, asset, balance FROM accounts
WHERE user_id = $1 AND asset = $2
`

type GetAccountByUserAssetParams struct {
	UserID pgtype.UUID
	Asset  string
}

func (q *Queries) GetAccountByUserAsset(ctx context.Context, arg GetAccountByUserAssetParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUserAsset, arg.UserID, arg.Asset)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Balance,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, asset, balance FROM accounts WHERE user_id = $1 ORDER BY asset
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Asset,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2
WHERE id = $1
RETURNING id, user_id, asset, balance
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID
	Balance pgtype.Numeric
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Balance,
	)
	return i, err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (id, user_id, asset, balance)  -- balance can remain 0; ledger is source of truth
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, asset) DO NOTHING
RETURNING id, user_id, asset, balance
`

type UpsertAccountParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Asset   string
	Balance pgtype.Numeric
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.ID,
		arg.UserID,
		arg.Asset,
		arg.Balance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Asset,
		&i.Balance,
	)
	return i, err
}
