// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (id, ref_type, ref_id)
VALUES ($1, $2, $3)
RETURNING id, ref_type, ref_id, created_at
`

type CreateLedgerParams struct {
	ID      pgtype.UUID
	RefType string
	RefID   pgtype.UUID
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, createLedger, arg.ID, arg.RefType, arg.RefID)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.CreatedAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (id, ledger_id, account_id, amount)
VALUES ($1, $2, $3, $4)
`

type InsertLedgerEntryParams struct {
	ID        pgtype.UUID
	LedgerID  pgtype.UUID
	AccountID pgtype.UUID
	Amount    pgtype.Numeric
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.LedgerID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}
