// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Asset   string
	Balance pgtype.Numeric
}

type Order struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Market    string
	Side      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	Remaining pgtype.Numeric
	Status    string
	CreatedAt pgtype.Timestamptz
}

type Trade struct {
	ID           pgtype.UUID
	TakerOrderID pgtype.UUID
	MakerOrderID pgtype.UUID
	Price        pgtype.Numeric
	Quantity     pgtype.Numeric
	TradedAt     pgtype.Timestamptz
}

type User struct {
	ID    pgtype.UUID
	Email pgtype.Text
}
