// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, user_id, market, side, price, quantity, remaining, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, market, side, price, quantity, remaining, status, created_at
`

type CreateOrderParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Market    string
	Side      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	Remaining pgtype.Numeric
	Status    string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Market,
		arg.Side,
		arg.Price,
		arg.Quantity,
		arg.Remaining,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Market,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.Remaining,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
