// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, user_id, market, side, price, quantity, remaining, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, market, side, price, quantity, remaining, status, created_at
`

type CreateOrderParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Market    string
	Side      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	Remaining pgtype.Numeric
	Status    string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.Market,
		arg.Side,
		arg.Price,
		arg.Quantity,
		arg.Remaining,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Market,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.Remaining,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, market, side, price, quantity, remaining, status, created_at FROM orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Market,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.Remaining,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, remaining = $3
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID        pgtype.UUID
	Status    string
	Remaining pgtype.Numeric
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status, arg.Remaining)
	return err
}
