// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTrade = `-- name: InsertTrade :one
INSERT INTO trades (
    id, taker_order_id,maker_order_id, price, quantity
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, taker_order_id, maker_order_id, price, quantity, traded_at
`

type InsertTradeParams struct {
	ID           pgtype.UUID
	TakerOrderID pgtype.UUID
	MakerOrderID pgtype.UUID
	Price        pgtype.Numeric
	Quantity     pgtype.Numeric
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.ID,
		arg.TakerOrderID,
		arg.MakerOrderID,
		arg.Price,
		arg.Quantity,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.TakerOrderID,
		&i.MakerOrderID,
		&i.Price,
		&i.Quantity,
		&i.TradedAt,
	)
	return i, err
}
