// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email
) VALUES (
    $1, $2
)
RETURNING id, email
`

type CreateUserParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, email)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type UpsertUserParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser, arg.ID, arg.Email)
	return err
}
